#!/usr/bin/env sh

0000-header
0010-actions
0020-apps
0021-apps-screenshot
0030-assign
0040-bar
0041-polybar
0050-bindings
0051-bindings-media
0060-exec
0070-gaps
0080-modes
0090-rofi
0100-scratchpad
0110-ui
0120-window-management
0130-workspaces

cat ~/.config/i3/conf.d/0* > ~/.config/i3/config_test

#if plasma
#kde-plasma 
